/* Generated by scripts/sync-store-photos.cjs — do not edit by hand */
import type { StoreGalleryImage } from "./store-gallery.types";

export const SYNCED_STORE_IMAGES: StoreGalleryImage[] = [
  { src: "/stores/1.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/2.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/3.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/4.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/5.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/6.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/7.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/8.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/9.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/10.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/13.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/14.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/15.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/16.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/17.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
  { src: "/stores/18.jpeg", caption: { id: "Bandar Laundry Express", en: "Bandar Laundry Express" } },
];
